name: Deploy to GHCR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: deploy

    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3

      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}

      -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.GITHUB_REPOSITORY }}:latest

      -
        name: Verify deployment
        run: echo "Deployment successful!"
